[package]
name = "alphavantage"
version = "0.1.0"
description = "Alpha Vantage client"
authors = ["António Marques <me@antoniomarques.eu>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/asmarques/alphavantage"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.8.6"
failure = "0.1.1"